[package]
name = "Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = { path = "../macroquad"}
#egui-macroquad = "*"
#egui = "*"
Simples_menu = { path = "../Simples_menu"}
serde = "*"
